### ISSUE TITLE
Wrong link address

### ISSUE THREAD

**Issue by lucallmon** [Alee14/YouTube-TV-Client#11]
youtube.com/tv no longer links to youtube tv. now it's https://tv.youtube.com/live

otherwise, it goes to youtube's homepage. 

the app looks great! but it's the wrong URL now. can it be fixed?

**Comment by Alee14** [comment]
Will fix it

**Comment by Alee14** [comment]
Hmm, yeah by the looks of it, they might have killed it?

**Comment by lucallmon** [comment]
Is it not working for you after you fixed the URL request?

**Comment by Alee14** [comment]
I haven't fully tested it yet, but I navigated to YouTube.com/tv on my browser and it still "worked" (as in it does show YouTube leanback but it will redirect to main YouTube)

**Comment by lucallmon** [comment]
Yes, definitely. But isn't this app's purpose to load into the official YouTubeTV infrastructure?

**Comment by Alee14** [comment]
> Yes, definitely. But isn't this app's purpose to load into the official YouTubeTV infrastructure?

It was meant for the old YouTube TV (originally called YouTube Leanback), before they discontinued it for desktop. But it still works on certain devices like Samsung TVs

**Comment by lucallmon** [comment]
I'm just trying to load it on a Linux Mint PC. Should that make a difference?

**Comment by Alee14** [comment]
It shouldn't, I have tested my application and it seems to work?
![image](https://github.com/Alee14/YouTube-TV-Client/assets/11698947/8d3e090b-bebc-4e4d-940f-d0b4a3c0762c)

**Comment by lucallmon** [comment]
This is just YouTube, not YouTube TV. I thought this was an app for YouTube TV. Like this:
![screenTYT](https://github.com/Alee14/YouTube-TV-Client/assets/17592730/fa97c389-9946-4b46-b4cb-535eb1197856)

**Comment by Alee14** [comment]
Obviously yeah, that is YouTube TV. But before that, there was another "YouTube TV" which was the screenshot I mentioned above (YouTube Leanback or YouTube for TV). It was linked to youtube.com/tv and at the time I called it "YouTube TV" or "Leanback". That being said, I probably should correct this and reflect more towards Leanback, not YouTube TV.

**Comment by lucallmon** [comment]
Gotcha. That's why I was confused. It would be kewl to have it do both. The interface works great!
